name: myeyez
favicon: null
layout_spectrum: 0.6067765399347991
typography_spectrum: 0.6103540293406695
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.12327669560909271
  lightness: 0.7880943475756794
  saturation: 0.7287135205697268
  rhythmicContrast: 0.7316402164287865
purpose: []
